apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: vpn-core-vm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: wireguard
          image: vpn-core-vm-wireguard:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: wireguard-udp
              containerPort: 51820
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: WG_CONFIG_PATH
              value: /etc/wireguard/wg0.conf
            - name: WG_INTERFACE
              value: wg0
          volumeMounts:
            - name: wireguard-config
              mountPath: /etc/wireguard/wg0.conf
              subPath: wg0.conf
              readOnly: true
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: wireguard-config
          secret:
            secretName: wireguard-config
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
